 CREATE TABLE "GCG_4426_EMP_DOCS"(
 "EMPLOYEE" CHAR(5),
 "DOC_ID" INTEGER,
 "CAT_ID" INTEGER,
 "DATE_COMPLETED" DATE DEFAULT '1900-01-01',
 "LINK_ID" IDENTITY DEFAULT '0',
 "COMPLETED_FLAG" BIT DEFAULT '0' NOT NULL ,
 "SUPERVISOR" VARCHAR(50),
 "DEACT" BIT DEFAULT '0',
 UNIQUE ("LINK_ID"));