CREATE TABLE "GCG_4426_CATEGORIES"(
 "CAT_ID" IDENTITY DEFAULT '0',
 "CAT_NAME" VARCHAR(15),
 "CAT_DESC" VARCHAR(50),
 "INACTIVE_FLAG" BIT DEFAULT '0' NOT NULL ,
 "CREATE_DT" DATE,
 "CREATE_USER" VARCHAR(8),
 "INACT_DT" DATE,
 "INACT_USER" VARCHAR(8),
 UNIQUE ("CAT_ID"));